// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCart.Data;

#nullable disable

namespace ShoppingCart.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330154612_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("ShoppingCart.Data.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts", (string)null);
                });

            modelBuilder.Entity("ShoppingCart.Data.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceWhenAdded")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems", (string)null);
                });

            modelBuilder.Entity("ShoppingCart.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Currency = "USD",
                            Description = "Compact wireless mouse with USB receiver",
                            IsActive = true,
                            Name = "Wireless Mouse Logitech M185",
                            Price = 14.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Currency = "USD",
                            Description = "RGB mechanical gaming keyboard",
                            IsActive = true,
                            Name = "Mechanical Keyboard Redragon K552",
                            Price = 49.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            Currency = "USD",
                            Description = "Ultra HD IPS display monitor",
                            IsActive = true,
                            Name = "Dell 27-inch 4K Monitor",
                            Price = 329.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            Currency = "USD",
                            Description = "Noise cancelling wireless headphones",
                            IsActive = true,
                            Name = "Sony WH-1000XM5 Headphones",
                            Price = 399.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            Currency = "USD",
                            Description = "High-speed external solid state drive",
                            IsActive = true,
                            Name = "Samsung 1TB SSD T7 Portable",
                            Price = 119.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            Currency = "USD",
                            Description = "Wireless multi-touch trackpad",
                            IsActive = true,
                            Name = "Apple Magic Trackpad",
                            Price = 129.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            Currency = "USD",
                            Description = "Multiport adapter with HDMI and USB",
                            IsActive = true,
                            Name = "Anker USB-C Hub 7-in-1",
                            Price = 39.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            Currency = "USD",
                            Description = "Full HD webcam for streaming",
                            IsActive = true,
                            Name = "Logitech C920 HD Webcam",
                            Price = 79.99m,
                            StockQuantity = 5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            Currency = "USD",
                            Description = "Wireless monochrome laser printer",
                            IsActive = true,
                            Name = "HP LaserJet Pro Printer",
                            Price = 189.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Currency = "USD",
                            Description = "Wireless earbuds with noise cancellation",
                            IsActive = true,
                            Name = "Apple AirPods Pro 2nd Gen",
                            Price = 249.00m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            Currency = "USD",
                            Description = "Smart speaker with Alexa",
                            IsActive = true,
                            Name = "Amazon Echo Dot 5th Gen",
                            Price = 50.00m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            Currency = "USD",
                            Description = "Ergonomic wired gaming mouse",
                            IsActive = true,
                            Name = "Razer DeathAdder Gaming Mouse",
                            Price = 59.99m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            Currency = "USD",
                            Description = "Full HD curved gaming monitor",
                            IsActive = true,
                            Name = "Samsung 32-inch Curved Monitor",
                            Price = 219.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            Currency = "USD",
                            Description = "Portable external hard drive USB 3.0",
                            IsActive = true,
                            Name = "WD 2TB External HDD",
                            Price = 79.99m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            Currency = "USD",
                            Description = "DDR4 desktop memory kit",
                            IsActive = true,
                            Name = "Corsair Vengeance 16GB RAM",
                            Price = 69.99m,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            Currency = "USD",
                            Description = "Desktop CPU 10-core performance",
                            IsActive = true,
                            Name = "Intel Core i5 13400 Processor",
                            Price = 239.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            Currency = "USD",
                            Description = "High performance gaming GPU",
                            IsActive = true,
                            Name = "NVIDIA RTX 4060 Graphics Card",
                            Price = 400.00m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            Currency = "USD",
                            Description = "Dual-band high-speed router",
                            IsActive = true,
                            Name = "TP-Link WiFi 6 Router",
                            Price = 129.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            Currency = "USD",
                            Description = "13-inch laptop with M2 chip",
                            IsActive = true,
                            Name = "Apple MacBook Air M2",
                            Price = 1099.00m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Currency = "USD",
                            Description = "Business ultrabook laptop",
                            IsActive = true,
                            Name = "Lenovo ThinkPad X1 Carbon",
                            Price = 1399.00m,
                            StockQuantity = 2
                        });
                });

            modelBuilder.Entity("ShoppingCart.Data.Entities.CartItem", b =>
                {
                    b.HasOne("ShoppingCart.Data.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoppingCart.Data.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("ShoppingCart.Data.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
